### ISSUE TITLE
Please share the design doc for this project

### ISSUE THREAD

**Issue by rahulnagar8** [koroder/train-delay-predictor#1] opened 2018-12-17 06:54 UTC
I would like to share some ideas to improve the model, would be helpful if you could share the design doc.

**Comment by rahulnagar8** [comment] 2018-12-17 06:55
Just found it. Never mind.

**Comment by koroder** [comment] 2018-12-17 10:20
The design doc is contained within the repo: https://github.com/koroder/train-delay-predictor/blob/master/report/final_proj_report.pdf

May I make a polite request to search in the repo before opening the issue :)

Also note that since the system was designed 4 years ago, we have been increasingly moving towards realm of unsupervised learning backed by probabilistic modelling. It would be a good idea to discuss this further if you are interested. Feel free to connect.

**Closed as completed by koroder** 2018-12-17 10:20 UTC
